<a href="https://colab.research.google.com/github/alzimna/Portfolio/blob/main/Automated%20Scraping/Crawling%20Tweet/Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source : https://helmisatria.com/blog/updated-crawl-data-twitter-x-maret-2024

In [12]:
#@title Twitter Auth Token

twitter_auth_token = 'masukkan auth token anda' # change this auth token

In [6]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.20).
gnupg is already the newest version (2.2.27-3ubuntu2.3).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.19.2-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
v20.19.2

In [9]:
# Crawl Data

filename = 'timnas.csv'
search_keyword = 'timnas since:2025-06-01 until:2025-06-10 lang:id'
limit = 100

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/timnas.csv, renaming to ./tweets-data/timnas.old.csv

-- Scrolling... (1)
Filling in keywords: timnas since:2025-06-01 until:2025-06-10 lang:id

 (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 18

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 34

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 49

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 66

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 83

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 97

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/timnas.csv
Total tweets saved: 110

--Taking a break, waiting for 10 seconds...
Got 110 tweets, done scrolling...
⠙

In [10]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1932223563190440352,Mon Jun 09 23:49:31 +0000 2025,0,Gue demen banget ngeliat komentar netizen indo...,1932223563190440352,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/193222356319044...,1760264260016656384,NaN
1,1931894016422895720,Mon Jun 09 23:49:19 +0000 2025,0,@tvOneNews Harta pak Prabowo 1 7 triliyun kalo...,1932223515253715244,NaN,tvOneNews,in,NaN,0,1,0,https://x.com/undefined/status/193222351525371...,1911545062304911360,NaN
2,1932223195085746285,Mon Jun 09 23:48:03 +0000 2025,11,Walter Samuel akan tetap menjadi asisten pela...,1932223195085746285,https://pbs.twimg.com/media/GtCiwOBasAEJmBn.jpg,NaN,in,NaN,0,1,2,https://x.com/undefined/status/193222319508574...,334492893,NaN
3,1932223140253577504,Mon Jun 09 23:47:50 +0000 2025,0,vision+ paytv private 7 hari only 15.000. yuk ...,1932223140253577504,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/193222314025357...,1298907556031553537,NaN
4,1932039732072255616,Mon Jun 09 23:47:36 +0000 2025,0,@unmagnetism Sipaling timnas,1932223081143300194,NaN,unmagnetism,in,NaN,0,0,0,https://x.com/undefined/status/193222308114330...,1061685224428363778,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,1932200355133268081,Mon Jun 09 22:17:17 +0000 2025,0,Hari ini timnas day!,1932200355133268081,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/193220035513326...,2594509958,NaN
106,1932200230339912060,Mon Jun 09 22:16:48 +0000 2025,3,Ndes mau tanya rencana nanti sore mau nobar ti...,1932200230339912060,NaN,NaN,in,NaN,0,3,0,https://x.com/undefined/status/193220023033991...,966083473,NaN
107,1932199986927910918,Mon Jun 09 22:15:50 +0000 2025,0,wajar lah kita sebagai warga negara menuntut t...,1932199986927910918,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/193219998692791...,1370309552772505602,NaN
108,1932199778810814733,Mon Jun 09 22:15:00 +0000 2025,2,Pelatih timnas Indonesia Patrick Kluivert memb...,1932199778810814733,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/193219977881081...,68930552,NaN
109,1931654471547023560,Mon Jun 09 22:13:23 +0000 2025,0,@hexohmismine @royanooo18 @Najiiiib6 @jerryarv...,1932199370113655127,NaN,hexohmismine,in,NaN,0,1,0,https://x.com/undefined/status/193219937011365...,1499751858612551682,NaN

In [11]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 110.